spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_library
    username: postgres
    password: Moni@202211
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /api

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: luv2code
    key-store: classpath:luv2code-keystore.p12
    key-store-password: secret
    key-store-type: PKCS12

okta:
  oauth2:
    client-id: 0oafa50v36ddnOPcM5d7
    issuer: https://dev-42503668.okta.com/oauth2/default

stripe:
  key:
    secrect: sk_test_51Op8sySIBpSifjWyuQ0sYi08Lzs8URZbcUHOEWGDnZFdj010bWoB3lTGNwnPxxamQ9wL5RSyF5kq4vKEFdny6fMD00r39BG3bc
